// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfF8Cyw-ZM7RTlV9p6jQHvy1LsRh_e7MI',
    appId: '1:638131107111:web:27117a81b2174c9caea502',
    messagingSenderId: '638131107111',
    projectId: 'expirydeals-48316',
    authDomain: 'expirydeals-48316.firebaseapp.com',
    storageBucket: 'expirydeals-48316.firebasestorage.app',
    measurementId: 'G-XT479V469L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhyvJZO4R1HlgfGhX9hYRuI_ctjMMY0QQ',
    appId: '1:638131107111:android:29b6da1bc04a4454aea502',
    messagingSenderId: '638131107111',
    projectId: 'expirydeals-48316',
    storageBucket: 'expirydeals-48316.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9cIXgAFN2LCR7mZwqBOB6ZZD8cBzCaio',
    appId: '1:638131107111:ios:81384d1ed4ba7b8faea502',
    messagingSenderId: '638131107111',
    projectId: 'expirydeals-48316',
    storageBucket: 'expirydeals-48316.firebasestorage.app',
    iosBundleId: 'com.expriydeals.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9cIXgAFN2LCR7mZwqBOB6ZZD8cBzCaio',
    appId: '1:638131107111:ios:aa9939af0aa38cf8aea502',
    messagingSenderId: '638131107111',
    projectId: 'expirydeals-48316',
    storageBucket: 'expirydeals-48316.firebasestorage.app',
    iosBundleId: 'com.example.expriyDeals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfF8Cyw-ZM7RTlV9p6jQHvy1LsRh_e7MI',
    appId: '1:638131107111:web:02de6c60ea211cdcaea502',
    messagingSenderId: '638131107111',
    projectId: 'expirydeals-48316',
    authDomain: 'expirydeals-48316.firebaseapp.com',
    storageBucket: 'expirydeals-48316.firebasestorage.app',
    measurementId: 'G-T6RYVWH7BG',
  );

}