import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
    "title": "English",
    "code": "en",
    "sign-in": "Sign in",
    "delete": "Delete",
    "buy" : "Buy",
    "brand" : "Brand",
    "price" : "Price",
    "make_payment" : "Make Payment",
    "quantity" : "Quantity",
    "buy_now" : "Buy Now",
    "view_details" : "View Details",
    "language": "Language",
    "shiped" : "Shipped",
    "total_price" : "Total Price",
    "price_details" : "Price Details",
    "logout_message" : "Do you want to log out this profile?",
    "delete_message" : "Do you want to delete this account?",
    "banner_message":"Your order is on the way!",
    "shipping_info.app_bar_title": "Shipping Information",
    "shipping_info.section_title": "Shipping Information",
    "shipping_info.timeline_steps[0].description": "Arrived at Logistic Hub",
    "shipping_info.timeline_steps[1].description": "Package Picked Up",
    "shipping_info.timeline_steps[2].description": "Packed and Ready to Ship",
    "shipping_info.timeline_steps[3].description": "Order Confirmed",
    "order_details.app_bar_title": "Order Details",
    "order_details.shipping_info_title": "Shipping Information",
    "order_details.shipping_method": "Local Standard",
    "order_details.shipping_id_label": "Id: 42561",
    "order_details.timeline_steps[0].description": "Arrived at Logistic Hub",
    "order_details.timeline_steps[1].description": "Package Picked Up",
    "order_details.timeline_steps[2].description": "Order Confirmed",
    "order_details.delivery_address_title": "Delivery Address",
    "order_details.order_details_title": "Order Details",
    "order_details.order_id_label": "Order ID: ",
    "order_details.order_status_label": "Order Status: ",
    "my_orders.title": "My Orders",
    "my_orders.no_orders": "No orders available",
    "cart.title": "My Cart",
    "cart.no_cart": "No cart available",
    "cart.success_message": "Cart deleted",
    "cart.error_message": "An error occurred",
    "payment_webview.app_bar_title": "Payment",
    "payment_webview.error_message": "An error occurred",
    "payment_success.success_message": "Payment successful",
    "payment_details.date_label": "Date",
    "payment_details.transaction_id_label": "Transaction ID",
    "payment_details.name_label": "Name",
    "payment_details.amount_label": "Amount",
    "payment_details.total_label": "Total",
    "payment_details.download_pdf_button": "Get PDF receipt",
    "payment_details.go_to_homepage": "Go to homepage",
    "payment_details.error_message": "Error: {error}",
    "search_products.app_bar_title": "Search Products",
    "search_products.search_hint": "Search products",
    "search_products.filter_label": "Filter",
    "search_products.category_label": "Category",
    "search_products.no_categories": "No categories found",
    "search_products.no_products": "No products found",
    "search_products.no_matching_products": "No matching products found",
    "product.search_hint": "Search products",
    "product.no_products": "No products found",
    "product.no_matching_products": "No matching products found",
    "product_details.app_bar_title": "Product Details",
    "product_details.section_title": "Product Details",
    "product_details.visit_store_button": "Visit store",
    "product_details.add_to_cart_button": "Add to cart",
    "product_details.buy_now_button": "Buy now",
    "product_details.success_message": "Added to cart successfully",
    "product_details.error_messages.add_to_cart_failed": "Failed to add to cart",
    "product_details.error_messages.product_data_not_available": "Product data not available",
    "product_details.error_messages.seller_data_not_available": "Seller data not available",
    "checkout.app_bar_title": "Checkout",
    "checkout.price_details_title": "Price Details",
    "checkout.price_label": "Price ({item} item)",
    "checkout.total_payment_label": "Total Payment:",
    "checkout.standard_delivery_label": "Standard Delivery",
    "checkout.place_order_button": "Place Order",
    "checkout.error_message": "Please complete your address",
    "add_category.app_bar_title": "Add Category",
    "add_category.item_name_label": "Item Name",
    "add_category.upload_image_label": "Upload Image",
    "add_category.add_product_label": "Add Product",
    "add_category.save_button": "Save",
    "add_category.email_validation.empty": "Enter email",
    "add_category.email_validation.invalid": "Enter a valid email address",
    "add_product.app_bar_title": "Add Product",
    "add_product.upload_image_label": "Upload Image",
    "add_product.add_product_label": "Add Product",
    "add_product.item_name_label": "Item Name",
    "add_product.item_details_label": "Item Details",
    "add_product.category_label": "Category",
    "add_product.item_price_label": "Item Price",
    "add_product.item_quantity_label": "Item Quantity",
    "add_product.expiry_date_label": "Expiry Date",
    "add_product.days_hint": "Days",
    "add_product.discount_hint": "Discount %",
    "add_product.save_button": "Save",
    "add_product.validation.empty_email": "Enter email",
    "add_product.validation.invalid_email": "Enter a valid email address",
    "add_product.validation.empty_field": "Enter password",
    "profile.settings_section": "Settings",
    "profile.support_section": "Support",
    "profile.edit_profile_feature": "Edit Profile",
    "profile.my_orders_feature": "My Orders",
    "profile.language_feature": "Language",
    "profile.notification_feature": "Notification",
    "profile.change_password_feature": "Change Password",
    "profile.policies_feature": "Policies",
    "profile.about_us_feature": "About Us",
    "profile.logout_button": "Logout",
    "profile.error_message": "Profile data not available",
    "info.no_data_message": "No data available",
    "info.error_message": "Error loading data",
    "change_password.app_bar_title": "Change Password",
    "change_password.current_password_hint": "Current Password",
    "change_password.new_password_hint": "New Password",
    "change_password.confirm_password_hint": "Confirm Password",
    "change_password.change_password_button": "Change Password",
    "change_password.success_message": "Password changed successfully",
    "change_password.validation.empty_password": "Enter password",
    "edit_profile.app_bar_title": "Update Profile",
    "edit_profile.name_label": "Name",
    "edit_profile.email_label": "Email Address",
    "edit_profile.contact_label": "Contact Information",
    "edit_profile.address_label": "Address",
    "edit_profile.city_label": "City",
    "edit_profile.state_label": "State",
    "edit_profile.zipcode_label": "Zip Code",
    "edit_profile.country_label": "Country",
    "edit_profile.update_button": "Update",
    "edit_profile.success_message": "Profile updated",
    "shops.app_bar_title": "Shops",
    "shops.no_shops": "No shops found",
    "seller_profile.products_tab": "Products",
    "seller_profile.about_tab": "About",
    "seller_products.item_label": "Item ({count})",
    "seller_about.store_name_label": "Store Name: ",
    "seller_about.owner_name_label": "Owner Name: ",
    "seller_about.store_description_label": "Store Description: ",
    "seller_about.location_label": "Location",
    "seller_about.contact_information_label": "Contact Information",
    "sign_in.app_bar_title": "Sign In",
    "sign_in.header_title": "Hi, Welcome back!",
    "sign_in.header_subtitle": "Sign in to continue exploring the best deals",
    "sign_in.email_label": "Email",
    "sign_in.email_hint": "example@gmail.com",
    "sign_in.password_label": "Password",
    "sign_in.password_hint": "***********",
    "sign_in.forgot_password": "Forgot Password",
    "sign_in.continue_with_google": "Continue with google",
    "sign_in.footer_first_text": "Don’t have an account? ",
    "sign_in.footer_second_text": "Sign up",
    "sign_in.success_message": "Login successfully done",
    "sign_in.google_success_message": "Successfully logged in with Google",
    "sign_in.google_error_credentials": "This email is already registered with email-password. Please select another Google account.",
    "sign_in.google_error_message": "Google login failed",
    "sign_in.error_message": "Login failed",
    "sign_in.otp_error_message": "Failed",
    "sign_in.email_validation_empty": "Enter email",
    "sign_in.email_validation_invalid": "Enter a valid email address",
    "sign_in.password_validation_empty": "Enter password",
    "sign_in.forgot_password_error_empty_email": "Fill-up your valid email",
    "sign_in.forgot_password_error": "Error occurred",
    "reset_password.app_bar_title": "Reset Password",
    "reset_password.header_title": "Let’s secure your space.",
    "reset_password.header_subtitle": "Create a new password to secure your account.",
    "reset_password.new_password_label": "Enter New Password",
    "reset_password.new_password_hint": "***********",
    "reset_password.confirm_password_label": "Confirm Password",
    "reset_password.confirm_password_hint": "***********",
    "reset_password.update_button": "Update Password",
    "reset_password.success_message": "Reset password successfully done",
    "reset_password.error_message": "Error occurred",
    "otp_verify_forgot.app_bar_title": "OTP Verification",
    "otp_verify_forgot.header_title": "Verify Your Identity",
    "otp_verify_forgot.header_subtitle": "For your security, verify the code sent to your registered contact. Let’s confirm it’s you!",
    "otp_verify_forgot.confirm_button": "Confirm",
    "otp_verify_forgot.resend_code": "Resend code",
    "otp_verify_forgot.success_message": "Otp verification successfully done",
    "otp_verify_forgot.error_message": "Error occurred",
    "otp_verify.app_bar_title": "OTP Verification",
    "otp_verify.header_title": "Enter OTP",
    "otp_verify.header_subtitle": "We have just sent you 6 digit code via your email.",
    "otp_verify.confirm_button": "Confirm",
    "otp_verify.resend_code_prefix": "Didn’t receive code? ",
    "otp_verify.resend_code": "Resend code",
    "otp_verify.success_message": "Otp verification successfully done",
    "otp_verify.error_message": "Error occurred",
    "verify_email.app_bar_title": "Verify Email",
    "verify_email.header_title": "Check Email",
    "verify_email.header_subtitle": "Please check your email to verify your account.",
    "verify_email.confirm_button": "Confirm Now",
    "verify_email_forgot.app_bar_title": "Check Email",
    "verify_email_forgot.header_title": "A letter has been sent.",
    "verify_email_forgot.header_subtitle": "Your next step is inside your inbox. Check your email to unlock it.",
    "verify_email_forgot.confirm_button": "Read My Letter",
    "sign_up.app_bar_title": "Sign Up",
    "sign_up.header_title": "Create New Account",
    "sign_up.header_subtitle": "Please fill your detail information.",
    "sign_up.full_name_label": "Full Name",
    "sign_up.full_name_hint": "Enter your full name",
    "sign_up.number_label": "Number",
    "sign_up.number_hint": "Enter your number",
    "sign_up.email_label": "Email",
    "sign_up.email_hint": "example@gmail.com",
    "sign_up.password_label": "Password",
    "sign_up.password_hint": "***********",
    "sign_up.verify_email_button": "Verify Email",
    "sign_up.footer_first_text": "Already have an account? ",
    "sign_up.footer_second_text": "Log In",
    "sign_up.success_message": "New user created",
    "sign_up.error_message": "Error occurred",
    "sign_up.name_validation_empty": "Enter name",
    "sign_up.number_validation_empty": "Enter number",
    "sign_up.email_validation_empty": "Enter email",
    "sign_up.email_validation_invalid": "Enter a valid email address",
    "sign_up.password_validation_empty": "Enter password",
    "home_screen.hello": "Hello",
    "home_screen.categories": "Categories",
    "home_screen.no_categories_available": "No categories available",
    "home_screen.special_offer": "Special Offer",
    "home_screen.see_all": "See all..",
    "home_screen.no_products_available": "No products available",
    "home_screen.nearby_stores": "Nearby Stores",
    "home_screen.no_shops_available": "No shops available",
    "home_screen.recommended_for_you": "Recommended for You",
    "all_category_screen.app_bar_title": "All Categories",
    "all_category_screen.no_categories_available": "No categories available",
    "main_button_navbar.home": "Home",
    "main_button_navbar.cart": "Cart",
    "main_button_navbar.list": "List",
    "main_button_navbar.profile": "Profile",
    "notification_screen.app_bar_title": "Notification",
    "notification_screen.all_notifications": "All notifications",
    "notification_screen.no_notification": "No notification",
    "review_screen.under_review": "Your application is under review",
    "review_screen.notify_approval": "We will notify you as soon as your account has been approved",
    "earning_screen.app_bar_title": "Earnings",
    "earning_screen.your_balance": "Your Balance",
    "earning_screen.withdraw": "Withdraw",
    "earning_screen.order_id": "Order ID",
    "earning_screen.customer": "Customer",
    "earning_screen.product_name": "Product name",
    "earning_screen.quantity": "Quantity",
    "earning_screen.status": "Status",
    "earning_screen.amount": "Amount",
    "earning_details_screen.app_bar_title": "Earning Details",
    "earning_details_screen.full_name_label": "Full name: ",
    "earning_details_screen.email_label": "Email: ",
    "earning_details_screen.number_label": "Number: ",
    "earning_details_screen.price_details": "Price Details",
    "earning_details_screen.transaction_id_label": "Transaction ID: ",
    "earning_details_screen.account_holder_name_label": "A/C holder name: ",
    "earning_details_screen.account_number_label": "A/C number: ",
    "earning_details_screen.received_amount_label": "Received amount: ",
    "earning_details_screen.deduct_percentage_label": "Deduct Percentage: ",
    "earning_details_screen.final_amount_label": "Final Amount: ",
    "onboarding_page.skip": "Skip",
    "onboarding_screen.get_started": "Get Started",
    "onboarding_screen.keep_reading": "Keep Reading",
    "onboarding_screen.begin_your_first_letter": "Begin Your First Letter",
    "onboarding_screen.page1_title": "Turn Near-Expiry Products into Sales!",
    "onboarding_screen.page1_subtitle": "Use our map view to find stores and products near you, or browse by categories.",
    "onboarding_screen.page2_title": "This is your space to care, to be heard, to feel safe.",
    "onboarding_screen.page3_title": "You are safe here. You are seen. You are heard.",
    "shipping_info_screen.app_bar_title": "Shipping Information",
    "shipping_info_screen.section_title": "Shipping Information",
    "shipping_info_screen.timeline_arrived_logistic_hub": "Arrived at Logistic Hub",
    "shipping_info_screen.timeline_package_picked_up": "Package Picked Up",
    "shipping_info_screen.timeline_packed_ready_to_ship": "Packed and Ready to Ship",
    "shipping_info_screen.timeline_order_confirmed": "Order Confirmed",
    "order_details_screen.app_bar_title": "Order Details",
    "order_details_screen.shipping_info_title": "Shipping Information",
    "order_details_screen.shipping_method": "Standard local",
    "order_details_screen.shipping_id_label": "Id: 42561",
    "order_details_screen.timeline_arrived_logistic_hub": "Arrived at Logistic Hub",
    "order_details_screen.timeline_package_picked_up": "Package Picked Up",
    "order_details_screen.timeline_order_confirmed": "Order Confirmed",
    "order_details_screen.delivery_address_title": "Delivery Address",
    "order_details_screen.order_details_title": "Order Details",
    "order_details_screen.order_id_label": "Order ID: ",
    "order_details_screen.order_status_label": "Order Status: ",
    "my_order_screen.title": "My Orders",
    "my_order_screen.no_orders": "No Order Available",
    "cart_screen.title": "My Cart",
    "cart_screen.no_cart": "No cart available",
    "cart_screen.success_message": "Deleted cart",
    "payment_webview_screen.app_bar_title": "Payment",
    "payment_success_screen.success_message": "Payment successful",
    "payment_details_screen.date_label": "Date",
    "payment_details_screen.transaction_id_label": "Transaction ID",
    "payment_details_screen.name_label": "Name",
    "payment_details_screen.amount_label": "Amount",
    "payment_details_screen.total_label": "Total",
    "payment_details_screen.download_pdf_button": "Get PDF receipt",
    "payment_details_screen.go_to_homepage": "Go to homepage",
    "payment_details_screen.error_message": "Error: {error}"
  },
        'es_ES': {
    "title": "Español",
    "code": "es",
    "sign-in": "Iniciar sesión",
    "shipping_info.app_bar_title": "Información de envío",
    "shipping_info.section_title": "Información de envío",
    "shipping_info.timeline_steps[0].description": "Llegó al centro logístico",
    "shipping_info.timeline_steps[1].description": "Paquete recogido",
    "shipping_info.timeline_steps[2].description": "Empacado y listo para enviar",
    "shipping_info.timeline_steps[3].description": "Pedido confirmado",
    "order_details.app_bar_title": "Detalles del pedido",
    "order_details.shipping_info_title": "Información de envío",
    "order_details.shipping_method": "Estándar local",
    "order_details.shipping_id_label": "ID: 42561",
    "order_details.timeline_steps[0].description": "Llegó al centro logístico",
    "order_details.timeline_steps[1].description": "Paquete recogido",
    "order_details.timeline_steps[2].description": "Pedido confirmado",
    "order_details.delivery_address_title": "Dirección de entrega",
    "order_details.order_details_title": "Detalles del pedido",
    "order_details.order_id_label": "ID del pedido: ",
    "order_details.order_status_label": "Estado del pedido: ",
    "my_orders.title": "Mis pedidos",
    "my_orders.no_orders": "No hay pedidos disponibles",
    "cart.title": "Mi carrito",
    "cart.no_cart": "No hay carrito disponible",
    "cart.success_message": "Carrito eliminado",
    "cart.error_message": "Ocurrió un error",
    "payment_webview.app_bar_title": "Pago",
    "payment_webview.error_message": "Ocurrió un error",
    "payment_success.success_message": "Pago exitoso",
    "payment_details.date_label": "Fecha",
    "payment_details.transaction_id_label": "ID de transacción",
    "payment_details.name_label": "Nombre",
    "payment_details.amount_label": "Monto",
    "payment_details.total_label": "Total",
    "payment_details.download_pdf_button": "Obtener recibo en PDF",
    "payment_details.go_to_homepage": "Ir a la página de inicio",
    "payment_details.error_message": "Error: {error}",
    "search_products.app_bar_title": "Buscar productos",
    "search_products.search_hint": "Buscar productos",
    "search_products.filter_label": "Filtrar",
    "search_products.category_label": "Categoría",
    "search_products.no_categories": "No se encontraron categorías",
    "search_products.no_products": "No se encontraron productos",
    "search_products.no_matching_products": "No se encontraron productos que coincidan",
    "product.search_hint": "Buscar productos",
    "product.no_products": "No se encontraron productos",
    "product.no_matching_products": "No se encontraron productos que coincidan",
    "product_details.app_bar_title": "Detalles del producto",
    "product_details.section_title": "Detalles del producto",
    "product_details.visit_store_button": "Visitar tienda",
    "product_details.add_to_cart_button": "Agregar al carrito",
    "product_details.buy_now_button": "Comprar ahora",
    "product_details.success_message": "Agregado al carrito exitosamente",
    "product_details.error_messages.add_to_cart_failed": "No se pudo agregar al carrito",
    "product_details.error_messages.product_data_not_available": "Datos del producto no disponibles",
    "product_details.error_messages.seller_data_not_available": "Datos del vendedor no disponibles",
    "checkout.app_bar_title": "Finalizar compra",
    "checkout.price_details_title": "Detalles del precio",
    "star": "Estrella",
    "checkout.price_label": "Precio ({item} artículo)",
    "checkout.total_payment_label": "Pago total:",
    "checkout.standard_delivery_label": "Entrega estándar",
    "checkout.place_order_button": "Realizar pedido",
    "checkout.error_message": "Por favor, completa tu dirección",
    "add_category.app_bar_title": "Agregar categoría",
    "add_category.item_name_label": "Nombre del artículo",
    "add_category.upload_image_label": "Subir imagen",
    "add_category.add_product_label": "Agregar producto",
    "add_category.save_button": "Guardar",
    "add_category.email_validation.empty": "Ingresa el correo electrónico",
    "add_category.email_validation.invalid": "Ingresa una dirección de correo electrónico válida",
    "add_product.app_bar_title": "Agregar producto",
    "add_product.upload_image_label": "Subir imagen",
    "add_product.add_product_label": "Agregar producto",
    "add_product.item_name_label": "Nombre del artículo",
    "add_product.item_details_label": "Detalles del artículo",
    "add_product.category_label": "Categoría",
    "add_product.item_price_label": "Precio del artículo",
    "add_product.item_quantity_label": "Cantidad del artículo",
    "add_product.expiry_date_label": "Fecha de vencimiento",
    "add_product.days_hint": "Días",
    "add_product.discount_hint": "Descuento %",
    "add_product.save_button": "Guardar",
    "add_product.validation.empty_email": "Ingresa el correo electrónico",
    "add_product.validation.invalid_email": "Ingresa una dirección de correo electrónico válida",
    "add_product.validation.empty_field": "Ingresa la contraseña",
    "profile.settings_section": "Configuración",
    "profile.support_section": "Soporte",
    "profile.edit_profile_feature": "Editar perfil",
    "profile.my_orders_feature": "Mis pedidos",
    "profile.language_feature": "Idioma",
    "profile.notification_feature": "Notificaciones",
    "profile.change_password_feature": "Cambiar contraseña",
    "profile.policies_feature": "Políticas",
    "profile.about_us_feature": "Sobre nosotros",
    "profile.logout_button": "Cerrar sesión",
    "profile.error_message": "Datos del perfil no disponibles",
    "info.no_data_message": "No hay datos disponibles",
    "info.error_message": "Error al cargar datos",
    "change_password.app_bar_title": "Cambiar contraseña",
    "change_password.current_password_hint": "Contraseña actual",
    "change_password.new_password_hint": "Nueva contraseña",
    "change_password.confirm_password_hint": "Confirmar contraseña",
    "change_password.change_password_button": "Cambiar contraseña",
    "change_password.success_message": "Contraseña cambiada exitosamente",
    "change_password.validation.empty_password": "Ingresa la contraseña",
    "edit_profile.app_bar_title": "Actualizar perfil",
    "edit_profile.name_label": "Nombre",
    "edit_profile.email_label": "Dirección de correo electrónico",
    "edit_profile.contact_label": "Información de contacto",
    "edit_profile.address_label": "Dirección",
    "edit_profile.city_label": "Ciudad",
    "edit_profile.state_label": "Estado",
    "edit_profile.zipcode_label": "Código postal",
    "edit_profile.country_label": "País",
    "edit_profile.update_button": "Actualizar",
    "edit_profile.success_message": "Perfil actualizado",
    "shops.app_bar_title": "Tiendas",
    "shops.no_shops": "No se encontraron tiendas",
    "seller_profile.products_tab": "Productos",
    "seller_profile.about_tab": "Acerca de",
    "seller_products.item_label": "Artículo ({count})",
    "seller_about.store_name_label": "Nombre de la tienda: ",
    "seller_about.owner_name_label": "Nombre del propietario: ",
    "seller_about.store_description_label": "Descripción de la tienda: ",
    "seller_about.location_label": "Ubicación",
    "seller_about.contact_information_label": "Información de contacto",
    "sign_in.app_bar_title": "Iniciar sesión",
    "sign_in.header_title": "¡Hola, bienvenido de nuevo!",
    "sign_in.header_subtitle": "Inicia sesión para seguir explorando las mejores ofertas",
    "sign_in.email_label": "Correo electrónico",
    "sign_in.email_hint": "ejemplo@gmail.com",
    "sign_in.password_label": "Contraseña",
    "sign_in.password_hint": "***********",
    "sign_in.forgot_password": "Olvidé mi contraseña",
    "sign_in.continue_with_google": "Continuar con Google",
    "sign_in.footer_first_text": "¿No tienes una cuenta? ",
    "sign_in.footer_second_text": "Regístrate",
    "sign_in.success_message": "Inicio de sesión exitoso",
    "sign_in.google_success_message": "Inicio de sesión con Google exitoso",
    "sign_in.google_error_credentials": "Este correo electrónico ya está registrado con correo y contraseña. Por favor, selecciona otra cuenta de Google.",
    "sign_in.google_error_message": "Error al iniciar sesión con Google",
    "sign_in.error_message": "Error al iniciar sesión",
    "sign_in.otp_error_message": "Falló",
    "sign_in.email_validation_empty": "Ingresa el correo electrónico",
    "sign_in.email_validation_invalid": "Ingresa una dirección de correo electrónico válida",
    "sign_in.password_validation_empty": "Ingresa la contraseña",
    "sign_in.forgot_password_error_empty_email": "Completa con un correo electrónico válido",
    "sign_in.forgot_password_error": "Ocurrió un error",
    "reset_password.app_bar_title": "Restablecer contraseña",
    "reset_password.header_title": "Aseguremos tu espacio.",
    "reset_password.header_subtitle": "Crea una nueva contraseña para proteger tu cuenta.",
    "reset_password.new_password_label": "Ingresa nueva contraseña",
    "reset_password.new_password_hint": "***********",
    "reset_password.confirm_password_label": "Confirmar contraseña",
    "reset_password.confirm_password_hint": "***********",
    "reset_password.update_button": "Actualizar contraseña",
    "reset_password.success_message": "Contraseña restablecida exitosamente",
    "reset_password.error_message": "Ocurrió un error",
    "otp_verify_forgot.app_bar_title": "Verificación de OTP",
    "otp_verify_forgot.header_title": "Verifica tu identidad",
    "otp_verify_forgot.header_subtitle": "Por tu seguridad, verifica el código enviado a tu contacto registrado. ¡Confirmemos que eres tú!",
    "otp_verify_forgot.confirm_button": "Confirmar",
    "otp_verify_forgot.resend_code": "Reenviar código",
    "otp_verify_forgot.success_message": "Verificación de OTP exitosa",
    "otp_verify_forgot.error_message": "Ocurrió un error",
    "otp_verify.app_bar_title": "Verificación de OTP",
    "otp_verify.header_title": "Ingresa el OTP",
    "otp_verify.header_subtitle": "Acabamos de enviarte un código de 6 dígitos a tu correo electrónico.",
    "otp_verify.confirm_button": "Confirmar",
    "otp_verify.resend_code_prefix": "¿No recibiste el código? ",
    "otp_verify.resend_code": "Reenviar código",
    "otp_verify.success_message": "Verificación de OTP exitosa",
    "otp_verify.error_message": "Ocurrió un error",
    "verify_email.app_bar_title": "Verificar correo electrónico",
    "verify_email.header_title": "Revisa tu correo",
    "verify_email.header_subtitle": "Por favor, revisa tu correo electrónico para verificar tu cuenta.",
    "verify_email.confirm_button": "Confirmar ahora",
    "verify_email_forgot.app_bar_title": "Revisa tu correo",
    "verify_email_forgot.header_title": "Se ha enviado una carta.",
    "verify_email_forgot.header_subtitle": "Tu próximo paso está en tu bandeja de entrada. Revisa tu correo para desbloquearlo.",
    "verify_email_forgot.confirm_button": "Leer mi carta",
    "sign_up.app_bar_title": "Registrarse",
    "sign_up.header_title": "Crear nueva cuenta",
    "sign_up.header_subtitle": "Por favor, completa tu información detallada.",
    "sign_up.full_name_label": "Nombre completo",
    "sign_up.full_name_hint": "Ingresa tu nombre completo",
    "sign_up.number_label": "Número",
    "sign_up.number_hint": "Ingresa tu número",
    "sign_up.email_label": "Correo electrónico",
    "sign_up.email_hint": "ejemplo@gmail.com",
    "sign_up.password_label": "Contraseña",
    "sign_up.password_hint": "***********",
    "sign_up.verify_email_button": "Verificar correo electrónico",
    "sign_up.footer_first_text": "¿Ya tienes una cuenta? ",
    "sign_up.footer_second_text": "Inicia sesión",
    "sign_up.success_message": "Nuevo usuario creado",
    "sign_up.error_message": "Ocurrió un error",
    "sign_up.name_validation_empty": "Ingresa el nombre",
    "sign_up.number_validation_empty": "Ingresa el número",
    "sign_up.email_validation_empty": "Ingresa el correo electrónico",
    "sign_up.email_validation_invalid": "Ingresa una dirección de correo electrónico válida",
    "sign_up.password_validation_empty": "Ingresa la contraseña",
    "home_screen.hello": "Hola",
    "home_screen.categories": "Categorías",
    "home_screen.no_categories_available": "No hay categorías disponibles",
    "home_screen.special_offer": "Oferta especial",
    "home_screen.see_all": "Ver todo..",
    "home_screen.no_products_available": "No hay productos disponibles",
    "home_screen.nearby_stores": "Tiendas cercanas",
    "home_screen.no_shops_available": "No hay tiendas disponibles",
    "home_screen.recommended_for_you": "Recomendado para ti",
    "all_category_screen.app_bar_title": "Todas las categorías",
    "all_category_screen.no_categories_available": "No hay categorías disponibles",
    "main_button_navbar.home": "Inicio",
    "main_button_navbar.cart": "Carrito",
    "main_button_navbar.list": "Lista",
    "main_button_navbar.profile": "Perfil",
    "notification_screen.app_bar_title": "Notificaciones",
    "notification_screen.all_notifications": "Todas las notificaciones",
    "notification_screen.no_notification": "No hay notificaciones",
    "review_screen.under_review": "Tu solicitud está en revisión",
    "review_screen.notify_approval": "Te notificaremos tan pronto como tu cuenta haya sido aprobada",
    "earning_screen.app_bar_title": "Ganancias",
    "earning_screen.your_balance": "Tu saldo",
    "earning_screen.withdraw": "Retirar",
    "earning_screen.order_id": "ID del pedido",
    "earning_screen.customer": "Cliente",
    "earning_screen.product_name": "Nombre del producto",
    "earning_screen.quantity": "Cantidad",
    "earning_screen.status": "Estado",
    "earning_screen.amount": "Monto",
    "earning_details_screen.app_bar_title": "Detalles de ganancias",
    "earning_details_screen.full_name_label": "Nombre completo: ",
    "earning_details_screen.email_label": "Correo electrónico: ",
    "earning_details_screen.number_label": "Número: ",
    "earning_details_screen.price_details": "Detalles del precio",
    "earning_details_screen.transaction_id_label": "ID de transacción: ",
    "earning_details_screen.account_holder_name_label": "Nombre del titular de la cuenta: ",
    "earning_details_screen.account_number_label": "Número de cuenta: ",
    "earning_details_screen.received_amount_label": "Monto recibido: ",
    "earning_details_screen.deduct_percentage_label": "Porcentaje deducido: ",
    "earning_details_screen.final_amount_label": "Monto final: ",
    "onboarding_page.skip": "Omitir",
    "onboarding_screen.get_started": "Comenzar",
    "onboarding_screen.keep_reading": "Sigue leyendo",
    "onboarding_screen.begin_your_first_letter": "Comienza tu primera carta",
    "onboarding_screen.page1_title": "¡Convierte productos próximos a vencer en ventas!",
    "onboarding_screen.page1_subtitle": "Usa nuestra vista de mapa para encontrar tiendas y productos cerca de ti, o explora por categorías.",
    "onboarding_screen.page2_title": "Este es tu espacio para cuidar, ser escuchado y sentirte seguro.",
    "onboarding_screen.page3_title": "Estás seguro aquí. Eres visto. Eres escuchado.",
    "shipping_info_screen.app_bar_title": "Información de envío",
    "shipping_info_screen.section_title": "Información de envío",
    "shipping_info_screen.timeline_arrived_logistic_hub": "Llegó al centro logístico",
    "shipping_info_screen.timeline_package_picked_up": "Paquete recogido",
    "shipping_info_screen.timeline_packed_ready_to_ship": "Empacado y listo para enviar",
    "shipping_info_screen.timeline_order_confirmed": "Pedido confirmado",
    "order_details_screen.app_bar_title": "Detalles del pedido",
    "order_details_screen.shipping_info_title": "Información de envío",
    "order_details_screen.shipping_method": "Estándar local",
    "order_details_screen.shipping_id_label": "ID: 42561",
    "order_details_screen.timeline_arrived_logistic_hub": "Llegó al centro logístico",
    "order_details_screen.timeline_package_picked_up": "Paquete recogido",
    "order_details_screen.timeline_order_confirmed": "Pedido confirmado",
    "order_details_screen.delivery_address_title": "Dirección de entrega",
    "order_details_screen.order_details_title": "Detalles del pedido",
    "order_details_screen.order_id_label": "ID del pedido: ",
    "order_details_screen.order_status_label": "Estado del pedido: ",
    "my_order_screen.title": "Mis pedidos",
    "my_order_screen.no_orders": "No hay pedidos disponibles",
    "cart_screen.title": "Mi carrito",
    "cart_screen.no_cart": "No hay carrito disponible",
    "cart_screen.success_message": "Carrito eliminado",
    "payment_webview_screen.app_bar_title": "Pago",
    "payment_success_screen.success_message": "Pago exitoso",
    "payment_details_screen.date_label": "Fecha",
    "payment_details_screen.transaction_id_label": "ID de transacción",
    "payment_details_screen.name_label": "Nombre",
    "payment_details_screen.amount_label": "Monto",
    "payment_details_screen.total_label": "Total",
    "payment_details_screen.download_pdf_button": "Obtener recibo en PDF",
    "payment_details_screen.go_to_homepage": "Ir a la página de inicio",
    "payment_details_screen.error_message": "Error: {error}"
  },
        'hi_IN': {
          'hello': 'नमस्ते',
          'language': 'भाषा',
        },
      };
}
