import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "title": "English",
          "code": "en",
          "sign-in": "Sign in",
          "delete": "Delete",
          "buy": "Buy",
          "brand": "Brand",
          "price": "Price",
          "make_payment": "Make Payment",
          "quantity": "Quantity",
          "buy_now": "Buy Now",
          "view_details": "View Details",
          "language": "Language",
          "shiped": "Shipped",
          "total_price": "Total Price",
          "price_details": "Price Details",
          "payment_requesta_done": "Payment request done",
          "logout_message": "Do you want to log out this profile?",
          "delete_message": "Do you want to delete this account?",
          "banner_message": "Your order is on the way!",
          "agree_condition.agree": "I agree to the ",
          "agree_condition.terms": "Terms & Conditions ",
          "agree_condition.and": "and ",
          "agree_condition.privacy": "Privacy Policy",
          "shipping_info.app_bar_title": "Shipping Information",
          "shipping_info.section_title": "Shipping Information",
          "shipping_info.timeline_steps[0].description": "Arrived at Logistic Hub",
          "shipping_info.timeline_steps[1].description": "Package Picked Up",
          "shipping_info.timeline_steps[2].description": "Packed and Ready to Ship",
          "shipping_info.timeline_steps[3].description": "Order Confirmed",
          "order_details.app_bar_title": "Order Details",
          "order_details.shipping_info_title": "Shipping Information",
          "order_details.shipping_method": "Local Standard",
          "order_details.shipping_id_label": "Id: 42561",
          "order_details.timeline_steps[0].description": "Arrived at Logistic Hub",
          "order_details.timeline_steps[1].description": "Package Picked Up",
          "order_details.timeline_steps[2].description": "Order Confirmed",
          "order_details.delivery_address_title": "Delivery Address",
          "order_details.order_details_title": "Order Details",
          "order_details.order_id_label": "Order ID: ",
          "order_details.order_status_label": "Order Status: ",
          "my_orders.title": "My Orders",
          "my_orders.no_orders": "No orders available",
          "cart.title": "My Cart",
          "cart.no_cart": "No cart available",
          "cart.success_message": "Cart deleted",
          "cart.error_message": "An error occurred",
          "payment_webview.app_bar_title": "Payment",
          "payment_webview.error_message": "An error occurred",
          "payment_success.success_message": "Payment successful",
          "payment_details.date_label": "Date",
          "payment_details.transaction_id_label": "Transaction ID",
          "payment_details.name_label": "Name",
          "payment_details.amount_label": "Amount",
          "payment_details.total_label": "Total",
          "payment_details.download_pdf_button": "Get PDF receipt",
          "payment_details.go_to_homepage": "Go to homepage",
          "payment_details.error_message": "Error: {error}",
          "search_products.app_bar_title": "Search Products",
          "search_products.search_hint": "Search products",
          "search_products.filter_label": "Filter",
          "search_products.category_label": "Category",
          "search_products.no_categories": "No categories found",
          "search_products.no_products": "No products found",
          "search_products.no_matching_products": "No matching products found",
          "product.search_hint": "Search products",
          "product.no_products": "No products found",
          "product.no_matching_products": "No matching products found",
          "product_details.app_bar_title": "Product Details",
          "product_details.section_title": "Product Details",
          "product_details.visit_store_button": "Visit store",
          "product_details.add_to_cart_button": "Add to cart",
          "product_details.buy_now_button": "Buy now",
          "product_details.success_message": "Added to cart successfully",
          "product_details.error_messages.add_to_cart_failed": "Failed to add to cart",
          "product_details.error_messages.product_data_not_available": "Product data not available",
          "product_details.error_messages.seller_data_not_available": "Seller data not available",
          "checkout.app_bar_title": "Checkout",
          "checkout.price_details_title": "Price Details",
          "checkout.price_label": "Price ({item} item)",
          "checkout.total_payment_label": "Total Payment:",
          "checkout.standard_delivery_label": "Standard Delivery",
          "checkout.place_order_button": "Place Order",
          "checkout.error_message": "Please complete your address",
          "add_category.app_bar_title": "Add Category",
          "add_category.item_name_label": "Item Name",
          "add_category.upload_image_label": "Upload Image",
          "add_category.add_product_label": "Add Product",
          "add_category.save_button": "Save",
          "add_category.email_validation.empty": "Enter email",
          "add_category.email_validation.invalid": "Enter a valid email address",
          "add_product.app_bar_title": "Add Product",
          "add_product.upload_image_label": "Upload Image",
          "add_product.add_product_label": "Add Product",
          "add_product.item_name_label": "Item Name",
          "add_product.item_details_label": "Item Details",
          "add_product.category_label": "Category",
          "add_product.item_price_label": "Item Price",
          "add_product.item_quantity_label": "Item Quantity",
          "add_product.expiry_date_label": "Expiry Date",
          "add_product.days_hint": "Days",
          "add_product.discount_hint": "Discount %",
          "add_product.save_button": "Save",
          "add_product.validation.empty_email": "Enter email",
          "add_product.validation.invalid_email": "Enter a valid email address",
          "add_product.validation.empty_field": "Enter password",
          "profile.settings_section": "Settings",
          "profile.support_section": "Support",
          "profile.edit_profile_feature": "Edit Profile",
          "profile.my_orders_feature": "My Orders",
          "profile.language_feature": "Language",
          "profile.notification_feature": "Notification",
          "profile.change_password_feature": "Change Password",
          "profile.policies_feature": "Policies",
          "profile.about_us_feature": "About Us",
          "profile.logout_button": "Logout",
          "profile.error_message": "Profile data not available",
          "info.no_data_message": "No data available",
          "info.error_message": "Error loading data",
          "change_password.app_bar_title": "Change Password",
          "change_password.current_password_hint": "Current Password",
          "change_password.new_password_hint": "New Password",
          "change_password.error_messages.passwords_do_not_match": "Passwords do not match",
          "change_password.confirm_password_hint": "Confirm Password",
          "change_password.change_password_button": "Change Password",
          "change_password.success_message": "Password changed successfully",
          "change_password.validation.empty_password": "Enter password",
          "change_password.validation.empty_password_must": "Password must be at least 6 characters",
          "edit_profile.app_bar_title": "Update Profile",
          "edit_profile.name_label": "Name",
          "edit_profile.email_label": "Email Address",
          "edit_profile.contact_label": "Contact Information",
          "edit_profile.address_label": "Address",
          "edit_profile.city_label": "City",
          "edit_profile.state_label": "State",
          "edit_profile.zipcode_label": "Zip Code",
          "edit_profile.country_label": "Country",
          "edit_profile.update_button": "Update",
          "edit_profile.success_message": "Profile updated",
          "shops.app_bar_title": "Shops",
          "shops.no_shops": "No shops found",
          "seller_profile.products_tab": "Products",
          "seller_profile.about_tab": "About",
          "seller_products.item_label": "Item ({count})",
          "seller_about.store_name_label": "Store Name: ",
          "seller_about.owner_name_label": "Owner Name: ",
          "seller_about.store_description_label": "Store Description: ",
          "seller_about.location_label": "Location",
          "seller_about.contact_information_label": "Contact Information",
          "forgot_password.app_bar_title": "Forgot Password",
          "forgot_password.header_title": "No worries!",
          "forgot_password.header_subtitle": "subtitle",
          "forgot_password.email_label": "Email Address",
          "forgot_password.no_email": "No email",
          "sign_in.app_bar_title": "Sign In",
          "sign_in.header_title": "Hi, Welcome back!",
          "sign_in.header_subtitle": "Sign in to continue exploring the best deals",
          "sign_in.email_label": "Email",
          "sign_in.email_hint": "example@gmail.com",
          "sign_in.password_label": "Password",
          "sign_in.password_hint": "***********",
          "sign_in.forgot_password": "Forgot Password",
          "sign_in.continue_with_google": "Continue with google",
          "sign_in.footer_first_text": "Don’t have an account? ",
          "sign_in.footer_second_text": "Sign up",
          "sign_in.success_message": "Login successfully done",
          "sign_in.google_success_message": "Successfully logged in with Google",
          "sign_in.google_error_credentials": "This email is already registered with email-password. Please select another Google account.",
          "sign_in.google_error_message": "Google login failed",
          "sign_in.error_message": "Login failed",
          "sign_in.otp_error_message": "Failed",
          "sign_in.email_validation_empty": "Enter email",
          "sign_in.email_validation_invalid": "Enter a valid email address",
          "sign_in.password_validation_empty": "Enter password",
          "sign_in.forgot_password_error_empty_email": "Fill-up your valid email",
          "sign_in.forgot_password_error": "Error occurred",
          "reset_password.app_bar_title": "Reset Password",
          "reset_password.header_title": "Let’s secure your space.",
          "reset_password.header_subtitle": "Create a new password to secure your account.",
          "reset_password.new_password_label": "Enter New Password",
          "reset_password.new_password_hint": "***********",
          "reset_password.confirm_password_label": "Confirm Password",
          "reset_password.confirm_password_hint": "***********",
          "reset_password.update_button": "Update Password",
          "reset_password.success_message": "Reset password successfully done",
          "reset_password.error_message": "Error occurred",
          "otp_verify_forgot.app_bar_title": "OTP Verification",
          "otp_verify_forgot.header_title": "Verify Your Identity",
          "otp_verify_forgot.header_subtitle": "For your security, verify the code sent to your registered contact. Let’s confirm it’s you!",
          "otp_verify_forgot.confirm_button": "Confirm",
          "otp_verify_forgot.resend_code": "Resend code",
          "otp_verify_forgot.success_message": "Otp verification successfully done",
          "otp_verify_forgot.error_message": "Enter a valid 6-digit OTP",
          "otp_verify.app_bar_title": "OTP Verification",
          "otp_verify.header_title": "Enter OTP",
          "otp_verify.header_subtitle": "We have just sent you 6 digit code via your email.",
          "otp_verify.confirm_button": "Confirm",
          "otp_verify.resend_code_prefix": "Didn’t receive code? ",
          "otp_verify.resend_code": "Resend code",
          "otp_verify.success_message": "Otp verification successfully done",
          "otp_verify.error_message": "Error occurred",
          "verify_email.app_bar_title": "Verify Email",
          "verify_email.header_title": "Check Email",
          "verify_email.header_subtitle": "Please check your email to verify your account.",
          "verify_email.confirm_button": "Confirm Now",
          "verify_email_forgot.app_bar_title": "Check Email",
          "verify_email_forgot.header_title": "A letter has been sent.",
          "verify_email_forgot.header_subtitle": "Your next step is inside your inbox. Check your email to unlock it.",
          "verify_email_forgot.confirm_button": "Read My Letter",
          "sign_up.app_bar_title": "Sign Up",
          "sign_up.header_title": "Create New Account",
          "sign_up.header_subtitle": "Please fill your detail information.",
          "sign_up.full_name_label": "Full Name",
          "sign_up.full_name_hint": "Enter your full name",
          "sign_up.number_label": "Number",
          "sign_up.number_hint": "Enter your number",
          "sign_up.email_label": "Email",
          "sign_up.email_hint": "example@gmail.com",
          "sign_up.password_label": "Password",
          "sign_up.password_hint": "***********",
          "sign_up.verify_email_button": "Verify Email",
          "sign_up.footer_first_text": "Already have an account? ",
          "sign_up.footer_second_text": "Log In",
          "sign_up.success_message": "New user created",
          "sign_up.error_message": "Error occurred",
          "sign_up.name_validation_empty": "Enter name",
          "sign_up.number_validation_empty": "Enter number",
          "sign_up.email_validation_empty": "Enter email",
          "sign_up.email_validation_invalid": "Enter a valid email address",
          "sign_up.password_validation_empty": "Enter password",
          "home_screen.hello": "Hello",
          "home_screen.categories": "Categories",
          "home_screen.no_categories_available": "No categories available",
          "home_screen.special_offer": "Special Offer",
          "home_screen.see_all": "See all..",
          "home_screen.no_products_available": "No products available",
          "home_screen.nearby_stores": "Nearby Stores",
          "home_screen.no_shops_available": "No shops available",
          "home_screen.recommended_for_you": "Recommended for You",
          "all_category_screen.app_bar_title": "All Categories",
          "all_category_screen.no_categories_available": "No categories available",
          "main_button_navbar.home": "Home",
          "main_button_navbar.cart": "Cart",
          "main_button_navbar.list": "List",
          "main_button_navbar.profile": "Profile",
          "notification_screen.app_bar_title": "Notification",
          "notification_screen.all_notifications": "All notifications",
          "notification_screen.no_notification": "No notification",
          "review_screen.under_review": "Your application is under review",
          "review_screen.notify_approval": "We will notify you as soon as your account has been approved",
          "earning_screen.app_bar_title": "Earnings",
          "earning_screen.your_balance": "Your Balance",
          "earning_screen.withdraw": "Withdraw",
          "earning_screen.order_id": "Order ID",
          "earning_screen.customer": "Customer",
          "earning_screen.product_name": "Product name",
          "earning_screen.quantity": "Quantity",
          "earning_screen.status": "Status",
          "earning_screen.amount": "Amount",
          "earning_details_screen.app_bar_title": "Earning Details",
          "earning_details_screen.full_name_label": "Full name: ",
          "earning_details_screen.email_label": "Email: ",
          "earning_details_screen.number_label": "Number: ",
          "earning_details_screen.price_details": "Price Details",
          "earning_details_screen.transaction_id_label": "Transaction ID: ",
          "earning_details_screen.account_holder_name_label": "A/C holder name: ",
          "earning_details_screen.account_number_label": "A/C number: ",
          "earning_details_screen.received_amount_label": "Received amount: ",
          "earning_details_screen.deduct_percentage_label": "Deduct Percentage: ",
          "earning_details_screen.final_amount_label": "Final Amount: ",
          "onboarding_page.skip": "Skip",
          "onboarding_screen.get_started": "Get Started",
          "onboarding_screen.keep_reading": "Keep Reading",
          "onboarding_screen.begin_your_first_letter": "Begin Your First Letter",
          "onboarding_screen.page1_title": "Turn Near-Expiry Products into Sales!",
          "onboarding_screen.page1_subtitle": "Use our map view to find stores and products near you, or browse by categories.",
          "onboarding_screen.page2_title": "This is your space to care, to be heard, to feel safe.",
          "onboarding.page2_subtitle": "",
          "onboarding_screen.page3_title": "You are safe here. You are seen. You are heard.",
          "shipping_info_screen.app_bar_title": "Shipping Information",
          "shipping_info_screen.section_title": "Shipping Information",
          "shipping_info_screen.timeline_arrived_logistic_hub": "Arrived at Logistic Hub",
          "shipping_info_screen.timeline_package_picked_up": "Package Picked Up",
          "shipping_info_screen.timeline_packed_ready_to_ship": "Packed and Ready to Ship",
          "shipping_info_screen.timeline_order_confirmed": "Order Confirmed",
          "order_details_screen.app_bar_title": "Order Details",
          "order_details_screen.shipping_info_title": "Shipping Information",
          "order_details_screen.shipping_method": "Standard local",
          "order_details_screen.shipping_id_label": "Id: 42561",
          "order_details_screen.timeline_arrived_logistic_hub": "Arrived at Logistic Hub",
          "order_details_screen.timeline_package_picked_up": "Package Picked Up",
          "order_details_screen.timeline_order_confirmed": "Order Confirmed",
          "order_details_screen.delivery_address_title": "Delivery Address",
          "order_details_screen.order_details_title": "Order Details",
          "order_details_screen.order_id_label": "Order ID: ",
          "order_details_screen.order_status_label": "Order Status: ",
          "my_order_screen.title": "My Orders",
          "my_order_screen.no_orders": "No Order Available",
          "cart_screen.title": "My Cart",
          "cart_screen.no_cart": "No cart available",
          "cart_screen.success_message": "Deleted cart",
          "payment_webview_screen.app_bar_title": "Payment",
          "payment_success_screen.success_message": "Payment successful",
          "payment_details_screen.date_label": "Date",
          "payment_details_screen.transaction_id_label": "Transaction ID",
          "payment_details_screen.name_label": "Name",
          "payment_details_screen.amount_label": "Amount",
          "payment_details_screen.total_label": "Total",
          "payment_details_screen.download_pdf_button": "Get PDF receipt",
          "payment_details_screen.go_to_homepage": "Go to homepage",
          "payment_details_screen.error_message": "Error: {error}"
        },
        'es_ES': {
          "title": "Español",
          "code": "es",
          "sign-in": "Iniciar sesión",
          "delete": "Eliminar",
          "buy": "Comprar",
          "brand": "Marca",
          "price": "Precio",
          "make_payment": "Realizar pago",
          "quantity": "Cantidad",
          "buy_now": "Comprar ahora",
          "view_details": "Ver detalles",
          "language": "Idioma",
          "shiped": "Enviado",
          "total_price": "Precio total",
          "price_details": "Detalles del precio",
          "payment_requesta_done": "Solicitud de pago realizada",
          "logout_message": "¿Quieres cerrar sesión en este perfil?",
          "delete_message": "¿Quieres eliminar esta cuenta?",
          "banner_message": "¡Tu pedido está en camino!",
          "agree_condition.agree": "Acepto los ",
          "agree_condition.terms": "Términos y Condiciones ",
          "agree_condition.and": "y ",
          "agree_condition.privacy": "Política de Privacidad",
          "shipping_info.app_bar_title": "Información de envío",
          "shipping_info.section_title": "Información de envío",
          "shipping_info.timeline_steps[0].description": "Llegó al centro logístico",
          "shipping_info.timeline_steps[1].description": "Paquete recogido",
          "shipping_info.timeline_steps[2].description": "Empacado y listo para enviar",
          "shipping_info.timeline_steps[3].description": "Pedido confirmado",
          "order_details.app_bar_title": "Detalles del pedido",
          "order_details.shipping_info_title": "Información de envío",
          "order_details.shipping_method": "Estándar local",
          "order_details.shipping_id_label": "ID: 42561",
          "order_details.timeline_steps[0].description": "Llegó al centro logístico",
          "order_details.timeline_steps[1].description": "Paquete recogido",
          "order_details.timeline_steps[2].description": "Pedido confirmado",
          "order_details.delivery_address_title": "Dirección de entrega",
          "order_details.order_details_title": "Detalles del pedido",
          "order_details.order_id_label": "ID del pedido: ",
          "order_details.order_status_label": "Estado del pedido: ",
          "my_orders.title": "Mis pedidos",
          "my_orders.no_orders": "No hay pedidos disponibles",
          "cart.title": "Mi carrito",
          "cart.no_cart": "No hay carrito disponible",
          "cart.success_message": "Carrito eliminado",
          "cart.error_message": "Ocurrió un error",
          "payment_webview.app_bar_title": "Pago",
          "payment_webview.error_message": "Ocurrió un error",
          "payment_success.success_message": "Pago exitoso",
          "payment_details.date_label": "Fecha",
          "payment_details.transaction_id_label": "ID de transacción",
          "payment_details.name_label": "Nombre",
          "payment_details.amount_label": "Monto",
          "payment_details.total_label": "Total",
          "payment_details.download_pdf_button": "Obtener recibo en PDF",
          "payment_details.go_to_homepage": "Ir a la página de inicio",
          "payment_details.error_message": "Error: {error}",
          "search_products.app_bar_title": "Buscar productos",
          "search_products.search_hint": "Buscar productos",
          "search_products.filter_label": "Filtrar",
          "search_products.category_label": "Categoría",
          "search_products.no_categories": "No se encontraron categorías",
          "search_products.no_products": "No se encontraron productos",
          "search_products.no_matching_products": "No se encontraron productos que coincidan",
          "product.search_hint": "Buscar productos",
          "product.no_products": "No se encontraron productos",
          "product.no_matching_products": "No se encontraron productos que coincidan",
          "product_details.app_bar_title": "Detalles del producto",
          "product_details.section_title": "Detalles del producto",
          "product_details.visit_store_button": "Visitar tienda",
          "product_details.add_to_cart_button": "Agregar al carrito",
          "product_details.buy_now_button": "Comprar ahora",
          "product_details.success_message": "Agregado al carrito exitosamente",
          "product_details.error_messages.add_to_cart_failed": "No se pudo agregar al carrito",
          "product_details.error_messages.product_data_not_available": "Datos del producto no disponibles",
          "product_details.error_messages.seller_data_not_available": "Datos del vendedor no disponibles",
          "checkout.app_bar_title": "Finalizar compra",
          "checkout.price_details_title": "Detalles del precio",
          "checkout.price_label": "Precio ({item} artículo)",
          "checkout.total_payment_label": "Pago total:",
          "checkout.standard_delivery_label": "Entrega estándar",
          "checkout.place_order_button": "Realizar pedido",
          "checkout.error_message": "Por favor, completa tu dirección",
          "add_category.app_bar_title": "Agregar categoría",
          "add_category.item_name_label": "Nombre del artículo",
          "add_category.upload_image_label": "Subir imagen",
          "add_category.add_product_label": "Agregar producto",
          "add_category.save_button": "Guardar",
          "add_category.email_validation.empty": "Ingresa el correo electrónico",
          "add_category.email_validation.invalid": "Ingresa una dirección de correo electrónico válida",
          "add_product.app_bar_title": "Agregar producto",
          "add_product.upload_image_label": "Subir imagen",
          "add_product.add_product_label": "Agregar producto",
          "add_product.item_name_label": "Nombre del artículo",
          "add_product.item_details_label": "Detalles del artículo",
          "add_product.category_label": "Categoría",
          "add_product.item_price_label": "Precio del artículo",
          "add_product.item_quantity_label": "Cantidad del artículo",
          "add_product.expiry_date_label": "Fecha de vencimiento",
          "add_product.days_hint": "Días",
          "add_product.discount_hint": "Descuento %",
          "add_product.save_button": "Guardar",
          "add_product.validation.empty_email": "Ingresa el correo electrónico",
          "add_product.validation.invalid_email": "Ingresa una dirección de correo electrónico válida",
          "add_product.validation.empty_field": "Ingresa la contraseña",
          "profile.settings_section": "Configuración",
          "profile.support_section": "Soporte",
          "profile.edit_profile_feature": "Editar perfil",
          "profile.my_orders_feature": "Mis pedidos",
          "profile.language_feature": "Idioma",
          "profile.notification_feature": "Notificaciones",
          "profile.change_password_feature": "Cambiar contraseña",
          "profile.policies_feature": "Políticas",
          "profile.about_us_feature": "Sobre nosotros",
          "profile.logout_button": "Cerrar sesión",
          "profile.error_message": "Datos del perfil no disponibles",
          "info.no_data_message": "No hay datos disponibles",
          "info.error_message": "Error al cargar datos",
          "change_password.app_bar_title": "Cambiar contraseña",
          "change_password.current_password_hint": "Contraseña actual",
          "change_password.new_password_hint": "Nueva contraseña",
          "change_password.error_messages.passwords_do_not_match": "Las contraseñas no coinciden",
          "change_password.confirm_password_hint": "Confirmar contraseña",
          "change_password.change_password_button": "Cambiar contraseña",
          "change_password.success_message": "Contraseña cambiada exitosamente",
          "change_password.validation.empty_password": "Ingresa la contraseña",
          "change_password.validation.empty_password_must": "La contraseña debe tener al menos 6 caracteres",
          "edit_profile.app_bar_title": "Actualizar perfil",
          "edit_profile.name_label": "Nombre",
          "edit_profile.email_label": "Dirección de correo electrónico",
          "edit_profile.contact_label": "Información de contacto",
          "edit_profile.address_label": "Dirección",
          "edit_profile.city_label": "Ciudad",
          "edit_profile.state_label": "Estado",
          "edit_profile.zipcode_label": "Código postal",
          "edit_profile.country_label": "País",
          "edit_profile.update_button": "Actualizar",
          "edit_profile.success_message": "Perfil actualizado",
          "shops.app_bar_title": "Tiendas",
          "shops.no_shops": "No se encontraron tiendas",
          "seller_profile.products_tab": "Productos",
          "seller_profile.about_tab": "Acerca de",
          "seller_products.item_label": "Artículo ({count})",
          "seller_about.store_name_label": "Nombre de la tienda: ",
          "seller_about.owner_name_label": "Nombre del propietario: ",
          "seller_about.store_description_label": "Descripción de la tienda: ",
          "seller_about.location_label": "Ubicación",
          "seller_about.contact_information_label": "Información de contacto",
          "forgot_password.app_bar_title": "Olvidé mi contraseña",
          "forgot_password.header_title": "¡No te preocupes!",
          "forgot_password.header_subtitle": "Subtítulo",
          "forgot_password.email_label": "Dirección de correo electrónico",
          "forgot_password.no_email": "No hay correo electrónico",
          "sign_in.app_bar_title": "Iniciar sesión",
          "sign_in.header_title": "¡Hola, bienvenido de nuevo!",
          "sign_in.header_subtitle": "Inicia sesión para seguir explorando las mejores ofertas",
          "sign_in.email_label": "Correo electrónico",
          "sign_in.email_hint": "ejemplo@gmail.com",
          "sign_in.password_label": "Contraseña",
          "sign_in.password_hint": "***********",
          "sign_in.forgot_password": "Olvidé mi contraseña",
          "sign_in.continue_with_google": "Continuar con Google",
          "sign_in.footer_first_text": "¿No tienes una cuenta? ",
          "sign_in.footer_second_text": "Regístrate",
          "sign_in.success_message": "Inicio de sesión exitoso",
          "sign_in.google_success_message": "Inicio de sesión con Google exitoso",
          "sign_in.google_error_credentials": "Este correo electrónico ya está registrado con correo y contraseña. Por favor, selecciona otra cuenta de Google.",
          "sign_in.google_error_message": "Error al iniciar sesión con Google",
          "sign_in.error_message": "Error al iniciar sesión",
          "sign_in.otp_error_message": "Falló",
          "sign_in.email_validation_empty": "Ingresa el correo electrónico",
          "sign_in.email_validation_invalid": "Ingresa una dirección de correo electrónico válida",
          "sign_in.password_validation_empty": "Ingresa la contraseña",
          "sign_in.forgot_password_error_empty_email": "Completa con un correo electrónico válido",
          "sign_in.forgot_password_error": "Ocurrió un error",
          "reset_password.app_bar_title": "Restablecer contraseña",
          "reset_password.header_title": "Aseguremos tu espacio.",
          "reset_password.header_subtitle": "Crea una nueva contraseña para proteger tu cuenta.",
          "reset_password.new_password_label": "Ingresa nueva contraseña",
          "reset_password.new_password_hint": "***********",
          "reset_password.confirm_password_label": "Confirmar contraseña",
          "reset_password.confirm_password_hint": "***********",
          "reset_password.update_button": "Actualizar contraseña",
          "reset_password.success_message": "Contraseña restablecida exitosamente",
          "reset_password.error_message": "Ocurrió un error",
          "otp_verify_forgot.app_bar_title": "Verificación de OTP",
          "otp_verify_forgot.header_title": "Verifica tu identidad",
          "otp_verify_forgot.header_subtitle": "Por tu seguridad, verifica el código enviado a tu contacto registrado. ¡Confirmemos que eres tú!",
          "otp_verify_forgot.confirm_button": "Confirmar",
          "otp_verify_forgot.resend_code": "Reenviar código",
          "otp_verify_forgot.success_message": "Verificación de OTP exitosa",
          "otp_verify_forgot.error_message": "Ingresa un OTP válido de 6 dígitos",
          "otp_verify.app_bar_title": "Verificación de OTP",
          "otp_verify.header_title": "Ingresa el OTP",
          "otp_verify.header_subtitle": "Acabamos de enviarte un código de 6 dígitos a tu correo electrónico.",
          "otp_verify.confirm_button": "Confirmar",
          "otp_verify.resend_code_prefix": "¿No recibiste el código? ",
          "otp_verify.resend_code": "Reenviar código",
          "otp_verify.success_message": "Verificación de OTP exitosa",
          "otp_verify.error_message": "Ocurrió un error",
          "verify_email.app_bar_title": "Verificar correo electrónico",
          "verify_email.header_title": "Revisa tu correo",
          "verify_email.header_subtitle": "Por favor, revisa tu correo electrónico para verificar tu cuenta.",
          "verify_email.confirm_button": "Confirmar ahora",
          "verify_email_forgot.app_bar_title": "Revisa tu correo",
          "verify_email_forgot.header_title": "Se ha enviado una carta.",
          "verify_email_forgot.header_subtitle": "Tu próximo paso está en tu bandeja de entrada. Revisa tu correo para desbloquearlo.",
          "verify_email_forgot.confirm_button": "Leer mi carta",
          "sign_up.app_bar_title": "Registrarse",
          "sign_up.header_title": "Crear nueva cuenta",
          "sign_up.header_subtitle": "Por favor, completa tu información detallada.",
          "sign_up.full_name_label": "Nombre completo",
          "sign_up.full_name_hint": "Ingresa tu nombre completo",
          "sign_up.number_label": "Número",
          "sign_up.number_hint": "Ingresa tu número",
          "sign_up.email_label": "Correo electrónico",
          "sign_up.email_hint": "ejemplo@gmail.com",
          "sign_up.password_label": "Contraseña",
          "sign_up.password_hint": "***********",
          "sign_up.verify_email_button": "Verificar correo electrónico",
          "sign_up.footer_first_text": "¿Ya tienes una cuenta? ",
          "sign_up.footer_second_text": "Inicia sesión",
          "sign_up.success_message": "Nuevo usuario creado",
          "sign_up.error_message": "Ocurrió un error",
          "sign_up.name_validation_empty": "Ingresa el nombre",
          "sign_up.number_validation_empty": "Ingresa el número",
          "sign_up.email_validation_empty": "Ingresa el correo electrónico",
          "sign_up.email_validation_invalid": "Ingresa una dirección de correo electrónico válida",
          "sign_up.password_validation_empty": "Ingresa la contraseña",
          "home_screen.hello": "Hola",
          "home_screen.categories": "Categorías",
          "home_screen.no_categories_available": "No hay categorías disponibles",
          "home_screen.special_offer": "Oferta especial",
          "home_screen.see_all": "Ver todo..",
          "home_screen.no_products_available": "No hay productos disponibles",
          "home_screen.nearby_stores": "Tiendas cercanas",
          "home_screen.no_shops_available": "No hay tiendas disponibles",
          "home_screen.recommended_for_you": "Recomendado para ti",
          "all_category_screen.app_bar_title": "Todas las categorías",
          "all_category_screen.no_categories_available": "No hay categorías disponibles",
          "main_button_navbar.home": "Inicio",
          "main_button_navbar.cart": "Carrito",
          "main_button_navbar.list": "Lista",
          "main_button_navbar.profile": "Perfil",
          "notification_screen.app_bar_title": "Notificaciones",
          "notification_screen.all_notifications": "Todas las notificaciones",
          "notification_screen.no_notification": "No hay notificaciones",
          "review_screen.under_review": "Tu solicitud está en revisión",
          "review_screen.notify_approval": "Te notificaremos tan pronto como tu cuenta haya sido aprobada",
          "earning_screen.app_bar_title": "Ganancias",
          "earning_screen.your_balance": "Tu saldo",
          "earning_screen.withdraw": "Retirar",
          "earning_screen.order_id": "ID del pedido",
          "earning_screen.customer": "Cliente",
          "earning_screen.product_name": "Nombre del producto",
          "earning_screen.quantity": "Cantidad",
          "earning_screen.status": "Estado",
          "earning_screen.amount": "Monto",
          "earning_details_screen.app_bar_title": "Detalles de ganancias",
          "earning_details_screen.full_name_label": "Nombre completo: ",
          "earning_details_screen.email_label": "Correo electrónico: ",
          "earning_details_screen.number_label": "Número: ",
          "earning_details_screen.price_details": "Detalles del precio",
          "earning_details_screen.transaction_id_label": "ID de transacción: ",
          "earning_details_screen.account_holder_name_label": "Nombre del titular de la cuenta: ",
          "earning_details_screen.account_number_label": "Número de cuenta: ",
          "earning_details_screen.received_amount_label": "Monto recibido: ",
          "earning_details_screen.deduct_percentage_label": "Porcentaje deducido: ",
          "earning_details_screen.final_amount_label": "Monto final: ",
          "onboarding_page.skip": "Omitir",
          "onboarding_screen.get_started": "Comenzar",
          "onboarding_screen.keep_reading": "Sigue leyendo",
          "onboarding_screen.begin_your_first_letter": "Comienza tu primera carta",
          "onboarding_screen.page1_title": "¡Convierte productos próximos a vencer en ventas!",
          "onboarding_screen.page1_subtitle": "Usa nuestra vista de mapa para encontrar tiendas y productos cerca de ti, o explora por categorías.",
          "onboarding_screen.page2_title": "Este es tu espacio para cuidar, ser escuchado y sentirte seguro.",
          "onboarding.page2_subtitle": "",
          "onboarding_screen.page3_title": "Estás seguro aquí. Eres visto. Eres escuchado.",
          "shipping_info_screen.app_bar_title": "Información de envío",
          "shipping_info_screen.section_title": "Información de envío",
          "shipping_info_screen.timeline_arrived_logistic_hub": "Llegó al centro logístico",
          "shipping_info_screen.timeline_package_picked_up": "Paquete recogido",
          "shipping_info_screen.timeline_packed_ready_to_ship": "Empacado y listo para enviar",
          "shipping_info_screen.timeline_order_confirmed": "Pedido confirmado",
          "order_details_screen.app_bar_title": "Detalles del pedido",
          "order_details_screen.shipping_info_title": "Información de envío",
          "order_details_screen.shipping_method": "Estándar local",
          "order_details_screen.shipping_id_label": "ID: 42561",
          "order_details_screen.timeline_arrived_logistic_hub": "Llegó al centro logístico",
          "order_details_screen.timeline_package_picked_up": "Paquete recogido",
          "order_details_screen.timeline_order_confirmed": "Pedido confirmado",
          "order_details_screen.delivery_address_title": "Dirección de entrega",
          "order_details_screen.order_details_title": "Detalles del pedido",
          "order_details_screen.order_id_label": "ID del pedido: ",
          "order_details_screen.order_status_label": "Estado del pedido: ",
          "my_order_screen.title": "Mis pedidos",
          "my_order_screen.no_orders": "No hay pedidos disponibles",
          "cart_screen.title": "Mi carrito",
          "cart_screen.no_cart": "No hay carrito disponible",
          "cart_screen.success_message": "Carrito eliminado",
          "payment_webview_screen.app_bar_title": "Pago",
          "payment_success_screen.success_message": "Pago exitoso",
          "payment_details_screen.date_label": "Fecha",
          "payment_details_screen.transaction_id_label": "ID de transacción",
          "payment_details_screen.name_label": "Nombre",
          "payment_details_screen.amount_label": "Monto",
          "payment_details_screen.total_label": "Total",
          "payment_details_screen.download_pdf_button": "Obtener recibo en PDF",
          "payment_details_screen.go_to_homepage": "Ir a la página de inicio",
          "payment_details_screen.error_message": "Error: {error}"
        },
        'hi_IN': {
          "title": "हिन्दी",
          "code": "hi",
          "sign-in": "साइन इन",
          "delete": "हटाएँ",
          "buy": "खरीदें",
          "brand": "ब्रांड",
          "price": "मूल्य",
          "make_payment": "भुगतान करें",
          "quantity": "मात्रा",
          "buy_now": "अभी खरीदें",
          "view_details": "विवरण देखें",
          "language": "भाषा",
          "shiped": "शिप किया गया",
          "total_price": "कुल मूल्य",
          "price_details": "मूल्य विवरण",
          "payment_requesta_done": "भुगतान अनुरोध पूर्ण",
          "logout_message": "क्या आप इस प्रोफाइल से लॉग आउट करना चाहते हैं?",
          "delete_message": "क्या आप इस खाते को हटाना चाहते हैं?",
          "banner_message": "आपका ऑर्डर रास्ते में है!",
          "agree_condition.agree": "मैं सहमत हूँ ",
          "agree_condition.terms": "नियम और शर्तें ",
          "agree_condition.and": "और ",
          "agree_condition.privacy": "गोपनीयता नीति",
          "shipping_info.app_bar_title": "शिपिंग जानकारी",
          "shipping_info.section_title": "शिपिंग जानकारी",
          "shipping_info.timeline_steps[0].description": "लॉजिस्टिक हब पर पहुँचा",
          "shipping_info.timeline_steps[1].description": "पैकेज उठाया गया",
          "shipping_info.timeline_steps[2].description": "पैक किया गया और शिप करने के लिए तैयार",
          "shipping_info.timeline_steps[3].description": "आर्डर की पुष्टि",
          "order_details.app_bar_title": "आर्डर विवरण",
          "order_details.shipping_info_title": "शिपिंग जानकारी",
          "order_details.shipping_method": "स्थानीय मानक",
          "order_details.shipping_id_label": "आईडी: 42561",
          "order_details.timeline_steps[0].description": "लॉजिस्टिक हब पर पहुँचा",
          "order_details.timeline_steps[1].description": "पैकेज उठाया गया",
          "order_details.timeline_steps[2].description": "आर्डर की पुष्टि",
          "order_details.delivery_address_title": "डिलीवरी पता",
          "order_details.order_details_title": "आर्डर विवरण",
          "order_details.order_id_label": "आर्डर आईडी: ",
          "order_details.order_status_label": "आर्डर स्थिति: ",
          "my_orders.title": "मेरे आर्डर",
          "my_orders.no_orders": "कोई आर्डर उपलब्ध नहीं",
          "cart.title": "मेरी कार्ट",
          "cart.no_cart": "कोई कार्ट उपलब्ध नहीं",
          "cart.success_message": "कार्ट हटाई गई",
          "cart.error_message": "एक त्रुटि हुई",
          "payment_webview.app_bar_title": "भुगतान",
          "payment_webview.error_message": "एक त्रुटि हुई",
          "payment_success.success_message": "भुगतान सफल",
          "payment_details.date_label": "तारीख",
          "payment_details.transaction_id_label": "लेनदेन आईडी",
          "payment_details.name_label": "नाम",
          "payment_details.amount_label": "राशि",
          "payment_details.total_label": "कुल",
          "payment_details.download_pdf_button": "पीडीएफ रसीद प्राप्त करें",
          "payment_details.go_to_homepage": "होमपेज पर जाएँ",
          "payment_details.error_message": "त्रुटि: {error}",
          "search_products.app_bar_title": "उत्पाद खोजें",
          "search_products.search_hint": "उत्पाद खोजें",
          "search_products.filter_label": "फ़िल्टर",
          "search_products.category_label": "श्रेणी",
          "search_products.no_categories": "कोई श्रेणियाँ नहीं मिलीं",
          "search_products.no_products": "कोई उत्पाद नहीं मिले",
          "search_products.no_matching_products": "कोई मिलते-जुलते उत्पाद नहीं मिले",
          "product.search_hint": "उत्पाद खोजें",
          "product.no_products": "कोई उत्पाद नहीं मिले",
          "product.no_matching_products": "कोई मिलते-जुलते उत्पाद नहीं मिले",
          "product_details.app_bar_title": "उत्पाद विवरण",
          "product_details.section_title": "उत्पाद विवरण",
          "product_details.visit_store_button": "दुकान पर जाएँ",
          "product_details.add_to_cart_button": "कार्ट में जोड़ें",
          "product_details.buy_now_button": "अभी खरीदें",
          "product_details.success_message": "कार्ट में सफलतापूर्वक जोड़ा गया",
          "product_details.error_messages.add_to_cart_failed": "कार्ट में जोड़ने में विफल",
          "product_details.error_messages.product_data_not_available": "उत्पाद डेटा उपलब्ध नहीं",
          "product_details.error_messages.seller_data_not_available": "विक्रेता डेटा उपलब्ध नहीं",
          "checkout.app_bar_title": "चेकआउट",
          "checkout.price_details_title": "मूल्य विवरण",
          "checkout.price_label": "मूल्य ({item} आइटम)",
          "checkout.total_payment_label": "कुल भुगतान:",
          "checkout.standard_delivery_label": "मानक डिलीवरी",
          "checkout.place_order_button": "आर्डर दें",
          "checkout.error_message": "कृपया अपना पता पूरा करें",
          "add_category.app_bar_title": "श्रेणी जोड़ें",
          "add_category.item_name_label": "आइटम का नाम",
          "add_category.upload_image_label": "छवि अपलोड करें",
          "add_category.add_product_label": "उत्पाद जोड़ें",
          "add_category.save_button": "सहेजें",
          "add_category.email_validation.empty": "ईमेल दर्ज करें",
          "add_category.email_validation.invalid": "एक मान्य ईमेल पता दर्ज करें",
          "add_product.app_bar_title": "उत्पाद जोड़ें",
          "add_product.upload_image_label": "छवि अपलोड करें",
          "add_product.add_product_label": "उत्पाद जोड़ें",
          "add_product.item_name_label": "आइटम का नाम",
          "add_product.item_details_label": "आइटम विवरण",
          "add_product.category_label": "श्रेणी",
          "add_product.item_price_label": "आइटम मूल्य",
          "add_product.item_quantity_label": "आइटम मात्रा",
          "add_product.expiry_date_label": "समाप्ति तिथि",
          "add_product.days_hint": "दिन",
          "add_product.discount_hint": "छूट %",
          "add_product.save_button": "सहेजें",
          "add_product.validation.empty_email": "ईमेल दर्ज करें",
          "add_product.validation.invalid_email": "एक मान्य ईमेल पता दर्ज करें",
          "add_product.validation.empty_field": "पासवर्ड दर्ज करें",
          "profile.settings_section": "सेटिंग्स",
          "profile.support_section": "समर्थन",
          "profile.edit_profile_feature": "प्रोफाइल संपादित करें",
          "profile.my_orders_feature": "मेरे आर्डर",
          "profile.language_feature": "भाषा",
          "profile.notification_feature": "सूचना",
          "profile.change_password_feature": "पासवर्ड बदलें",
          "profile.policies_feature": "नीतियाँ",
          "profile.about_us_feature": "हमारे बारे में",
          "profile.logout_button": "लॉगआउट",
          "profile.error_message": "प्रोफाइल डेटा उपलब्ध नहीं",
          "info.no_data_message": "कोई डेटा उपलब्ध नहीं",
          "info.error_message": "डेटा लोड करने में त्रुटि",
          "change_password.app_bar_title": "पासवर्ड बदलें",
          "change_password.current_password_hint": "वर्तमान पासवर्ड",
          "change_password.new_password_hint": "नया पासवर्ड",
          "change_password.error_messages.passwords_do_not_match": "पासवर्ड मेल नहीं खाते",
          "change_password.confirm_password_hint": "पासवर्ड की पुष्टि करें",
          "change_password.change_password_button": "पासवर्ड बदलें",
          "change_password.success_message": "पासवर्ड सफलतापूर्वक बदला गया",
          "change_password.validation.empty_password": "पासवर्ड दर्ज करें",
          "change_password.validation.empty_password_must": "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
          "edit_profile.app_bar_title": "प्रोफाइल अपडेट करें",
          "edit_profile.name_label": "नाम",
          "edit_profile.email_label": "ईमेल पता",
          "edit_profile.contact_label": "संपर्क जानकारी",
          "edit_profile.address_label": "पता",
          "edit_profile.city_label": "शहर",
          "edit_profile.state_label": "राज्य",
          "edit_profile.zipcode_label": "ज़िप कोड",
          "edit_profile.country_label": "देश",
          "edit_profile.update_button": "अपडेट करें",
          "edit_profile.success_message": "प्रोफाइल अपडेट की गई",
          "shops.app_bar_title": "दुकानें",
          "shops.no_shops": "कोई दुकानें नहीं मिलीं",
          "seller_profile.products_tab": "उत्पाद",
          "seller_profile.about_tab": "के बारे में",
          "seller_products.item_label": "आइटम ({count})",
          "seller_about.store_name_label": "दुकान का नाम: ",
          "seller_about.owner_name_label": "मालिक का नाम: ",
          "seller_about.store_description_label": "दुकान का विवरण: ",
          "seller_about.location_label": "स्थान",
          "seller_about.contact_information_label": "संपर्क जानकारी",
          "forgot_password.app_bar_title": "पासवर्ड भूल गए",
          "forgot_password.header_title": "कोई चिंता नहीं!",
          "forgot_password.header_subtitle": "उपशीर्षक",
          "forgot_password.email_label": "ईमेल पता",
          "forgot_password.no_email": "कोई ईमेल नहीं",
          "sign_in.app_bar_title": "साइन इन",
          "sign_in.header_title": "हाय, वापस स्वागत है!",
          "sign_in.header_subtitle": "सर्वोत्तम डील्स की खोज जारी रखने के लिए साइन इन करें",
          "sign_in.email_label": "ईमेल",
          "sign_in.email_hint": "example@gmail.com",
          "sign_in.password_label": "पासवर्ड",
          "sign_in.password_hint": "***********",
          "sign_in.forgot_password": "पासवर्ड भूल गए",
          "sign_in.continue_with_google": "Google के साथ जारी रखें",
          "sign_in.footer_first_text": "खाता नहीं है? ",
          "sign_in.footer_second_text": "साइन अप करें",
          "sign_in.success_message": "लॉगिन सफलतापूर्वक पूर्ण",
          "sign_in.google_success_message": "Google के साथ सफलतापूर्वक लॉगिन किया गया",
          "sign_in.google_error_credentials": "यह ईमेल पहले से ही ईमेल-पासवर्ड के साथ पंजीकृत है। कृपया दूसरा Google खाता चुनें।",
          "sign_in.google_error_message": "Google लॉगिन विफल",
          "sign_in.error_message": "लॉगिन विफल",
          "sign_in.otp_error_message": "विफल",
          "sign_in.email_validation_empty": "ईमेल दर्ज करें",
          "sign_in.email_validation_invalid": "एक मान्य ईमेल पता दर्ज करें",
          "sign_in.password_validation_empty": "पासवर्ड दर्ज करें",
          "sign_in.forgot_password_error_empty_email": "अपना मान्य ईमेल भरें",
          "sign_in.forgot_password_error": "एक त्रुटि हुई",
          "reset_password.app_bar_title": "पासवर्ड रीसेट करें",
          "reset_password.header_title": "आइए आपके स्थान को सुरक्षित करें।",
          "reset_password.header_subtitle": "अपने खाते को सुरक्षित करने के लिए एक नया पासवर्ड बनाएँ।",
          "reset_password.new_password_label": "नया पासवर्ड दर्ज करें",
          "reset_password.new_password_hint": "***********",
          "reset_password.confirm_password_label": "पासवर्ड की पुष्टि करें",
          "reset_password.confirm_password_hint": "***********",
          "reset_password.update_button": "पासवर्ड अपडेट करें",
          "reset_password.success_message": "पासवर्ड रीसेट सफलतापूर्वक पूर्ण",
          "reset_password.error_message": "एक त्रुटि हुई",
          "otp_verify_forgot.app_bar_title": "OTP सत्यापन",
          "otp_verify_forgot.header_title": "अपनी पहचान सत्यापित करें",
          "otp_verify_forgot.header_subtitle": "आपकी सुरक्षा के लिए, अपने पंजीकृत संपर्क पर भेजा गया कोड सत्यापित करें। आइए पुष्टि करें कि यह आप हैं!",
          "otp_verify_forgot.confirm_button": "पुष्टि करें",
          "otp_verify_forgot.resend_code": "कोड पुनः भेजें",
          "otp_verify_forgot.success_message": "OTP सत्यापन सफलतापूर्वक पूर्ण",
          "otp_verify_forgot.error_message": "6 अंकों का मान्य OTP दर्ज करें",
          "otp_verify.app_bar_title": "OTP सत्यापन",
          "otp_verify.header_title": "OTP दर्ज करें",
          "otp_verify.header_subtitle": "हमने अभी आपके ईमेल पर 6 अंकों का कोड भेजा है।",
          "otp_verify.confirm_button": "पुष्टि करें",
          "otp_verify.resend_code_prefix": "कोड प्राप्त नहीं हुआ? ",
          "otp_verify.resend_code": "कोड पुनः भेजें",
          "otp_verify.success_message": "OTP सत्यापन सफलतापूर्वक पूर्ण",
          "otp_verify.error_message": "एक त्रुटि हुई",
          "verify_email.app_bar_title": "ईमेल सत्यापित करें",
          "verify_email.header_title": "ईमेल जाँचें",
          "verify_email.header_subtitle": "कृपया अपने खाते को सत्यापित करने के लिए अपना ईमेल जाँचें।",
          "verify_email.confirm_button": "अब पुष्टि करें",
          "verify_email_forgot.app_bar_title": "ईमेल जाँचें",
          "verify_email_forgot.header_title": "एक पत्र भेजा गया है।",
          "verify_email_forgot.header_subtitle": "आपका अगला कदम आपके इनबॉक्स में है। इसे अनलॉक करने के लिए अपना ईमेल जाँचें।",
          "verify_email_forgot.confirm_button": "मेरा पत्र पढ़ें",
          "sign_up.app_bar_title": "साइन अप",
          "sign_up.header_title": "नया खाता बनाएँ",
          "sign_up.header_subtitle": "कृपया अपनी विस्तृत जानकारी भरें।",
          "sign_up.full_name_label": "पूरा नाम",
          "sign_up.full_name_hint": "अपना पूरा नाम दर्ज करें",
          "sign_up.number_label": "नंबर",
          "sign_up.number_hint": "अपना नंबर दर्ज करें",
          "sign_up.email_label": "ईमेल",
          "sign_up.email_hint": "example@gmail.com",
          "sign_up.password_label": "पासवर्ड",
          "sign_up.password_hint": "***********",
          "sign_up.verify_email_button": "ईमेल सत्यापित करें",
          "sign_up.footer_first_text": "पहले से खाता है? ",
          "sign_up.footer_second_text": "लॉग इन करें",
          "sign_up.success_message": "नया उपयोगकर्ता बनाया गया",
          "sign_up.error_message": "एक त्रुटि हुई",
          "sign_up.name_validation_empty": "नाम दर्ज करें",
          "sign_up.number_validation_empty": "नंबर दर्ज करें",
          "sign_up.email_validation_empty": "ईमेल दर्ज करें",
          "sign_up.email_validation_invalid": "एक मान्य ईमेल पता दर्ज करें",
          "sign_up.password_validation_empty": "पासवर्ड दर्ज करें",
          "home_screen.hello": "नमस्ते",
          "home_screen.categories": "श्रेणियाँ",
          "home_screen.no_categories_available": "कोई श्रेणियाँ उपलब्ध नहीं",
          "home_screen.special_offer": "विशेष ऑफर",
          "home_screen.see_all": "सभी देखें..",
          "home_screen.no_products_available": "कोई उत्पाद उपलब्ध नहीं",
          "home_screen.nearby_stores": "नजदीकी दुकानें",
          "home_screen.no_shops_available": "कोई दुकानें उपलब्ध नहीं",
          "home_screen.recommended_for_you": "आपके लिए अनुशंसित",
          "all_category_screen.app_bar_title": "सभी श्रेणियाँ",
          "all_category_screen.no_categories_available": "कोई श्रेणियाँ उपलब्ध नहीं",
          "main_button_navbar.home": "होम",
          "main_button_navbar.cart": "कार्ट",
          "main_button_navbar.list": "सूची",
          "main_button_navbar.profile": "प्रोफाइल",
          "notification_screen.app_bar_title": "सूचनाएँ",
          "notification_screen.all_notifications": "सभी सूचनाएँ",
          "notification_screen.no_notification": "कोई सूचना नहीं",
          "review_screen.under_review": "आपका आवेदन समीक्षा में है",
          "review_screen.notify_approval": "जैसे ही आपका खाता स्वीकृत होगा, हम आपको सूचित करेंगे",
          "earning_screen.app_bar_title": "आय",
          "earning_screen.your_balance": "आपका शेष",
          "earning_screen.withdraw": "निकालें",
          "earning_screen.order_id": "आर्डर आईडी",
          "earning_screen.customer": "ग्राहक",
          "earning_screen.product_name": "उत्पाद का नाम",
          "earning_screen.quantity": "मात्रा",
          "earning_screen.status": "स्थिति",
          "earning_screen.amount": "राशि",
          "earning_details_screen.app_bar_title": "आय विवरण",
          "earning_details_screen.full_name_label": "पूरा नाम: ",
          "earning_details_screen.email_label": "ईमेल: ",
          "earning_details_screen.number_label": "नंबर: ",
          "earning_details_screen.price_details": "मूल्य विवरण",
          "earning_details_screen.transaction_id_label": "लेनदेन आईडी: ",
          "earning_details_screen.account_holder_name_label": "खाता धारक का नाम: ",
          "earning_details_screen.account_number_label": "खाता संख्या: ",
          "earning_details_screen.received_amount_label": "प्राप्त राशि: ",
          "earning_details_screen.deduct_percentage_label": "कटौती प्रतिशत: ",
          "earning_details_screen.final_amount_label": "अंतिम राशि: ",
          "onboarding_page.skip": "छोड़ें",
          "onboarding_screen.get_started": "शुरू करें",
          "onboarding_screen.keep_reading": "पढ़ना जारी रखें",
          "onboarding_screen.begin_your_first_letter": "अपना पहला पत्र शुरू करें",
          "onboarding_screen.page1_title": "निकट-समाप्ति उत्पादों को बिक्री में बदलें!",
          "onboarding_screen.page1_subtitle": "हमारे मानचित्र दृश्य का उपयोग करके अपने पास की दुकानें और उत्पाद खोजें, या श्रेणियों द्वारा ब्राउज़ करें।",
          "onboarding_screen.page2_title": "यह आपका स्थान है जहाँ आपकी देखभाल की जाती है, सुना जाता है, और सुरक्षित महसूस करते हैं।",
          "onboarding.page2_subtitle": "",
          "onboarding_screen.page3_title": "आप यहाँ सुरक्षित हैं। आप देखे जाते हैं। आप सुने जाते हैं।",
          "shipping_info_screen.app_bar_title": "शिपिंग जानकारी",
          "shipping_info_screen.section_title": "शिपिंग जानकारी",
          "shipping_info_screen.timeline_arrived_logistic_hub": "लॉजिस्टिक हब पर पहुँचा",
          "shipping_info_screen.timeline_package_picked_up": "पैकेज उठाया गया",
          "shipping_info_screen.timeline_packed_ready_to_ship": "पैक किया गया और शिप करने के लिए तैयार",
          "shipping_info_screen.timeline_order_confirmed": "आर्डर की पुष्टि",
          "order_details_screen.app_bar_title": "आर्डर विवरण",
          "order_details_screen.shipping_info_title": "शिपिंग जानकारी",
          "order_details_screen.shipping_method": "स्थानीय मानक",
          "order_details_screen.shipping_id_label": "आईडी: 42561",
          "order_details_screen.timeline_arrived_logistic_hub": "लॉजिस्टिक हब पर पहुँचा",
          "order_details_screen.timeline_package_picked_up": "पैकेज उठाया गया",
          "order_details_screen.timeline_order_confirmed": "आर्डर की पुष्टि",
          "order_details_screen.delivery_address_title": "डिलीवरी पता",
          "order_details_screen.order_details_title": "आर्डर विवरण",
          "order_details_screen.order_id_label": "आर्डर आईडी: ",
          "order_details_screen.order_status_label": "आर्डर स्थिति: ",
          "my_order_screen.title": "मेरे आर्डर",
          "my_order_screen.no_orders": "कोई आर्डर उपलब्ध नहीं",
          "cart_screen.title": "मेरी कार्ट",
          "cart_screen.no_cart": "कोई कार्ट उपलब्ध नहीं",
          "cart_screen.success_message": "कार्ट हटाई गई",
          "payment_webview_screen.app_bar_title": "भुगतान",
          "payment_success_screen.success_message": "भुगतान सफल",
          "payment_details_screen.date_label": "तारीख",
          "payment_details_screen.transaction_id_label": "लेनदेन आईडी",
          "payment_details_screen.name_label": "नाम",
          "payment_details_screen.amount_label": "राशि",
          "payment_details_screen.total_label": "कुल",
          "payment_details_screen.download_pdf_button": "पीडीएफ रसीद प्राप्त करें",
          "payment_details_screen.go_to_homepage": "होमपेज पर जाएँ",
          "payment_details_screen.error_message": "त्रुटि: {error}"
        },
      };
}

 